---
title: "CA_final"
author: "Ashley Thomson"
date: "4/8/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(openxlsx)
library(janitor)
library(lubridate)
library(DT)
library(skimr)
library(plotly)
library(kableExtra)
library(epitools)
library(broom)
library(boot)
library(modeest)
library(tableone)
library(table1)
library(tidymodels)
```

```{r}
df <- read_csv("C:/Users/mtta1/Downloads/CA_Data.csv") %>% 
    clean_names() %>% 
    mutate(across(where(is.character), ~case_when(
        . == "Checked" ~ "1", 
        . == "Unchecked" ~ "0", 
        T ~ .
    ))) %>% 
    mutate(across(c("specimen_collection_date", "admission_date", "discharge_date", "death_date"), ~as.Date(., format = "%m/%d/%Y"))) %>% 
    type_convert() %>% 
    mutate(record_id = as.character(record_id), 
           age_bucket = case_when(
               between(age_in_years, 0, 17) ~ "0 - 17", 
               between(age_in_years, 18, 34) ~ "18 - 34", 
               between(age_in_years, 35, 49) ~ "35 - 49", 
               between(age_in_years, 50, 64) ~ "50 - 64", 
               between(age_in_years, 65, 79) ~ "65 - 79", 
               between(age_in_years, 80, 120) ~ "80+", 
               T ~ "err"
           ))
```

```{r}
# metadata
skim <- skim(df)
```

```{r}
# frequency tables of categorical fields
skim %>% 
    filter(between(character.n_unique, 2, 10)) %>% 
    pull(skim_variable) %>% 
    map(~df %>% 
            tabyl(.data[[.x]]))
```


```{r}

df$death <- factor(df$death,
                     levels = c("No","Yes"),
                     labels = c("No",
                                 "Yes"))

df$cv_picc <- factor(df$cv_picc,
                     levels = c(0,1),
                     labels = c("No",
                                 "Yes"))

df$g_j_tube <- factor(df$g_j_tube,
                     levels = c(0,1),
                     labels = c("No",
                                 "Yes"))

df$hemodialysis_port <- factor(df$hemodialysis_port,
                     levels = c(0,1),
                     labels = c("No",
                                 "Yes"))

df$mechanical_vent <- factor(df$mechanical_vent,
                     levels = c(0,1),
                     labels = c("No",
                                 "Yes"))

df$tracheostomy <- factor(df$tracheostomy,
                     levels = c(0,1),
                     labels = c("No",
                                 "Yes"))

df$peg_tube <- factor(df$peg_tube,
                     levels = c(0,1),
                     labels = c("No",
                                 "Yes"))

df$urinary_catheter <- factor(df$urinary_catheter,
                     levels = c(0,1),
                     labels = c("No",
                                 "Yes"))

df$wound_vac <- factor(df$wound_vac,
                     levels = c(0,1),
                     labels = c("No",
                                 "Yes"))

df$diabetes <- factor(df$diabetes,
                     levels = c(0,1),
                     labels = c("No",
                                 "Yes"))


df$copd <- factor(df$copd,
                     levels = c(0,1),
                     labels = c("No",
                                 "Yes"))

df$chf <- factor(df$chf,
                     levels = c(0,1),
                     labels = c("No",
                                 "Yes"))

df$respiratory_failure <- factor(df$respiratory_failure,
                     levels = c(0,1),
                     labels = c("No",
                                 "Yes"))

df$obesity <- factor(df$obesity,
                     levels = c(0,1),
                     labels = c("No",
                                 "Yes"))

df$wound_ulcer_abscess <- factor(df$wound_ulcer_abscess,
                     levels = c(0,1),
                     labels = c("No",
                                 "Yes"))

df$uti <- factor(df$uti,
                     levels = c(0,1),
                     labels = c("No",
                                 "Yes"))

df$cva <- factor(df$cva,
                     levels = c(0,1),
                     labels = c("No",
                                 "Yes"))
df$sepsis <- factor(df$sepsis,
                     levels = c(0,1),
                     labels = c("No",
                                 "Yes"))
df$cancer <- factor(df$cancer,
                     levels = c(0,1),
                     labels = c("No",
                                 "Yes"))


label(df$cv_picc) <- "CV/PICC"
label(df$g_j_tube) <- "G/J Tube"
label(df$hemodialysis_port) <- "Hemodialysis Port"
label(df$mechanical_vent) <- " Mechanical Vent"
label(df$tracheostomy) <- "Tracheostomoy"
label(df$peg_tube) <- "PEG Tube"
label(df$urinary_catheter) <- "Urinary Catheter"
label(df$wound_vac) <- "Wound VAC"
label(df$diabetes) <- "Diabetes"
label(df$copd) <- "COPD"
label(df$chf) <- "CHF"
label(df$respiratory_failure) <- "Respiratory Failure"
label(df$obesity) <- "Obesity"
label(df$wound_ulcer_abscess) <- "Wound/Ulcer/Abscess"
label(df$uti) <- "UTI"
label(df$cva) <- "CVA"
label(df$sepsis) <- "Sepsis"
label(df$cancer) <- "Cancer"
label(df$history_of_mdro) <- "History of MDRO"
label(df$death) <- "Did the patient die?"

units(df$age_bucket) <- "Years"

table1(~ age_bucket + 
           facility_type + 
           source + 
           cv_picc + 
           g_j_tube + 
           hemodialysis_port + 
           mechanical_vent + 
           tracheostomy + 
           peg_tube + 
           urinary_catheter + 
           wound_vac + 
           diabetes + 
           copd + 
           chf + 
           respiratory_failure + 
           obesity + 
           wound_ulcer_abscess + 
           uti + 
           cva + 
           sepsis + 
           cancer + 
           history_of_mdro | death, data = df, overall = "Total" )





```


**Other Fields**  
age_bucket
facility_type
source

**Invasive Devices**  
cv_picc
g_j_tube
hemodialysis_port
mechanical_vent
tracheostomy
peg_tube
urinary_catheter
wound_vac

**Comorbidities**  
diabetes
copd
chf
respiratory_failure
obesity
wound_ulcer_abscess
uti
cva
sepsis
cancer
history_of_mdro



```{r}
mod1 <- logistic_reg() %>% 
    fit(death~cv_picc
        + g_j_tube
        + hemodialysis_port
        + mechanical_vent
        + tracheostomy
        + peg_tube
        + urinary_catheter
        + wound_vac, 
        data = df)

tidy(mod1, exponentiate = T) %>% 
    slice(-1) %>% 
    arrange(p.value)
```














